language: rust
sudo: false

rust:
  - stable
  - beta
  - nightly

before_install: |
  version=$(grep "^version =" Cargo.toml | sed -r  's/^[^0-9]*([0-9]+.[0-9]+.[0-9]+).*/\1/') &&
  docs_version=$(grep -R 'docs\.rs' src | head -n 1 | sed -r 's/^[^0-9]*([0-9]+.[0-9]+.[0-9]+).*/\1/') &&
  test "$version" == "$docs_version"

notifications:
  email: false
